name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use API key
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "API_KEY value: $API_KEY"  # Debug output
          sed -i "s/const API_KEY = '';/const API_KEY = '${API_KEY}';/" assets/js/main.js
          cat assets/js/main.js  # Debug output