name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        run: mv * $GITHUB_WORKSPACE

      - name: Set API key
        run: echo "window.API_KEY = '${{ secrets.API_KEY }}';" >> $GITHUB_WORKSPACE/assets/js/main.js
