name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set API key environment variable
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Set API key
        run: echo "API_KEY = '${{ secrets.API_KEY }}';" >> $GITHUB_WORKSPACE/assets/js/main.js
