name: Deploy

on:
  push:
    branches:
      - origin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use API key
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Set API key
        run: echo "window.API_KEY = '${API_KEY}';" >> $GITHUB_WORKSPACE/assets/js/main.js

      - name: Deploy to GitHub Pages
        run: mv * $GITHUB_WORKSPACE
